### ISSUE TITLE
Notify about new messages when user has scrolled up

### ISSUE THREAD

**Issue by oandregal** [Automattic/happychat-client#118]
If the user scrolls up then they may be unaware of new inbound messages.

See 867-gh-happychat and 199-gh-happychat.

**Comment by nosolosw** [comment]
A potential mockup for this:

![101d3d14-0e44-11e7-92af-70c9687b1314](https://user-images.githubusercontent.com/583546/36371501-9c037458-1562-11e8-8064-be5213c94874.png)
