### ISSUE TITLE
Reuse Happychat in Calypso 

### ISSUE THREAD

**Issue by oandregal** [Automattic/happychat-client#152]
These are the approaches I was thinking of:

### Use the available dist target

We could take the `target/dist/happychat.js` and use it in Calypso by building a React/Redux wrapper on top of that. This is the approach we've followed to integrate the `directly` library in Calypso [see](https://github.com/Automattic/wp-calypso/tree/master/client/lib/directly).

### Create a new target that reuses the full library

This is the approach followed by the notifications-panel component in Calypso. See [calypso](https://github.com/Automattic/wp-calypso/tree/5742eb250b83932c017a899a61e79401c5ab24c3/client/notifications) and [notifications-panel](https://github.com/Automattic/notifications-panel).

This approach requires some tweaks to [integrate the CSS](https://github.com/Automattic/wp-calypso/blob/a70587157b33783ba4d5e0e4a1e136680d459d51/assets/stylesheets/_vendor.scss) and [teach webpack to process the React components from the npm package](https://github.com/Automattic/wp-calypso/blob/a5607732c563ae978a322964bb1df606fea85f3b/webpack.config.js#L116).

The component initializes [its own internal store](https://github.com/Automattic/notifications-panel/blob/master/src/Notifications.jsx#L6) that is separated from the target (Calypso). But it also uses [the Calypso Redux store](https://github.com/Automattic/wp-calypso/blob/5742eb250b83932c017a899a61e79401c5ab24c3/client/notifications/index.jsx#L249) to pass some props and action dispatchers.

### Create a new target that imports the separate components

The way this may work is:

- the npm package will export the React UI components (from `ui/`) and the Redux state reducer & middleware (from `state/`). They won't be connected together (we won't export `src/index` or `src/form`).
- the target (Calypso) will import them and connect them as necessary.

This may have the advantage to only import the components needed (no pulling of the contact form, for example).

**Comment by nosolosw** [comment]
For the record, this thread p7OimR-wc-p2 contains some valuable conversations.

**Comment by mattwondra** [comment]
@nosolosw In p7OimR-m0-p2 we expected to see "Happychat in a panel" by about now — I just wanted to confirm whether work on this has been started or not? That's really what we need to make this work in Calypso, so if work hasn't been started on that yet, that's likely where we'll need to begin.

**Comment by nosolosw** [comment]
@mattwondra that changed mid-project: although that was scheduled for v2, it wasn't a priority for woo and they prefer v2 to be focused on other things (tickets and so).

**Comment by nosolosw** [comment]
An issue that's relevant to this: https://github.com/Automattic/happychat-client/issues/50
