### ISSUE TITLE
Align back button and title in MessageForm component

### ISSUE THREAD

**Issue by oandregal** [Automattic/happychat-client#221]
The [`<MessageForm>` component](https://github.com/Automattic/happychat-client/tree/master/src/ui/components/message-form) can have a back button and a title, like this:

![back-and-title-proper](https://user-images.githubusercontent.com/583546/40231098-12f64514-5a9a-11e8-8868-cdfe575885b7.png)

If you take a closer look, though, they aren't properly aligned.

How to test:

* clone the repo
* edit the file `src/config/development.local.json` by changing `css_url` from `https://widgets.wp.com/happychat/` to `http://localhost:9000/`. This tells Happychat to use the local CSS, not the one we distribute over [our CDN](https://widgets.wp.com/happychat/happychat.css).
* execute `npm install && npm start`
* introduce some text in the text fields and click the submit button and you'll see the `<MessageForm>` component.

**Comment by nosolosw** [comment]
@evilluendas could I summon your magic CSS skills to help me with this?

Unlike Calypso, we don't have the `<HeaderCake>` component here. If this turns out not to be an easy fix I can look into pulling that component in.
