### ISSUE TITLE
Go back button

### ISSUE THREAD

**Issue by dwainm** [Automattic/happychat-client#223]
When there was a problem from data should persist.

When there was success form data should be removed.

**Comment by nosolosw** [comment]
Notes for this, we could use the HTTP status code to help with this:

- if the request was successful, the back button would take you to a clean from
- if the request failed, the back button would take you to a form with the values you typed

The [`status` reducer](https://github.com/Automattic/happychat-client/blob/master/src/state/fallbackTicket/reducer.js#L28) takes into account the response status code to fire the proper Redux action.

**Comment by dwainm** [comment]
On the WooCommerce.com implementation we return `400` when there was an issue with the submission and `200` on success.

**Comment by nosolosw** [comment]
Fixed at https://github.com/Automattic/happychat-client/pull/228
