### ISSUE TITLE
Add text helper / explanation alongside components

### ISSUE THREAD

**Issue by nosolosw** [Automattic/happychat-client#224]
Live validation that allows notices to be displayed in form ( above/below field ).

For the Woo example we specifically want to show a notice when the user selects a specific product.

**Comment by mattyza** [comment]
GIF example:

![wccom-ticket-subs-note](https://user-images.githubusercontent.com/880803/40051945-cf263e70-583c-11e8-82ec-ea531306f6b6.gif)

**Comment by nosolosw** [comment]
Fixed at https://github.com/Automattic/happychat-client/pull/235
