### ISSUE TITLE
Allow scrolling

### ISSUE THREAD

**Issue by jobthomas** [Automattic/happychat-client#254]
On woo.com it's currently not possible to access parts of a chat outside the visible area:

![http://cld.wthms.co/0qdJY0](http://cld.wthms.co/0qdJY0+)
Link to image here: http://cld.wthms.co/0qdJY0.

**Comment by nosolosw** [comment]
May be the case that your transcript session isn't long enough to show the scrollbar? AFAIK, only the last session is loaded, not the whole history. I've just tested and it's working properly (notice the greyish bar in the right):

![scroll](https://user-images.githubusercontent.com/583546/42879237-2ded9d88-8a90-11e8-8933-e7af69348327.png)

Tentatively closing as resolved. Please, if you can repro, reopen this and share the following details: browser, OS, and its corresponding versions.
