### ISSUE TITLE
script error when hit return key in dropdown search

### ISSUE THREAD

**Issue by haszari** [Automattic/happychat-client#263]
#### How to reproduce
- Get happychat running.
- Open `I need help with` dropdown.
- Type in search field.
- Hit enter key.
- => JS error `Cannot read property 'refs' of undefined` in browser console

<img width="612" alt="screen shot 2018-08-27 at 10 30 35 am" src="https://user-images.githubusercontent.com/4167300/44633825-416b7880-a9e4-11e8-801c-38a02993dd8c.png">

Looks like this is `activateItem()` method:

```js
	activateItem() {
		if ( ! this.state.isOpen ) {
			return this.openDropdown();
		}
		ReactDom.findDOMNode( this.refs[ 'item-' + this.focused ].refs.itemLink ).click();
	}
```

**Comment by nosolosw** [comment]
https://github.com/Automattic/happychat-client/pull/264 should fix this.

**Comment by nosolosw** [comment]
Fix is now merged.
