### ISSUE TITLE
Fixed height in iframe may cause submit button invisible

### ISSUE THREAD

**Issue by gedex** [Automattic/happychat-client#278]
Originally reported by @corsonr in WooCommerce.com:

**Describe the bug**

When resizing the textarea height the submit button becomes invisible since the form section isn't scrollable.

**To Reproduce**
1. Go to http://localhost:9000/.
2. Increase the height of the "What are you trying to do?" textarea.
3. See that the "Create ticket" button doesn't show and you can't scroll to make it show.

![fixed-height-issue](https://user-images.githubusercontent.com/78313/51228201-16c98e80-198a-11e9-8068-62de09efd62c.gif)

**Comment by bgrgicak** [comment]
I was unable to recreate this and it looks like the issue was fixed in this commit df4598ad0393b26ca3d17ac7985277bf09529f63.

The WooCommerce.com bug was related to an old version of Happychat client as described in [this PR](https://github.com/Automattic/woocommerce.com/pull/6897).
