### ISSUE TITLE
Duplicate items in product select dropdown

### ISSUE THREAD

**Issue by andfinally** [Automattic/happychat-client#340]
When you open the HappyChat client's product select dropdown on the WCCOM [Open a Support Request](https://woocommerce.com/my-account/create-a-ticket/) page, the list is filled with many duplicate items.

This doesn't seem to be related to the number of licences you have – for example, I only have two active subscriptions to Facebook for WooCommerce.

<img width="413" alt="image" src="https://user-images.githubusercontent.com/1647564/141768586-20245784-13b5-40bf-b2c7-f1b14d48a246.png">

**Comment by mattwondra** [comment]
@andfinally The items on that list are populated by the host system — in this case, WooCommerce.com. It seems more likely this is a problem on the Woo side than on the Happy Chat Client side.

Can you "View Source" on that page, look in the `happychatSettings` JS variable at the bottom of the page, and see if you those items are duplicated in the "itemList" array?

**Comment by andfinally** [comment]
Cheers @mattwondra, we'll sort it out!
