### ISSUE TITLE
Style the chat form

### ISSUE THREAD

**Issue by nosolosw** [Automattic/happychat-client#43]
so it can be told apart from a bare webpage. See p2-p7OimR-CY for details.

The current state of this is:

![chat-form](https://user-images.githubusercontent.com/583546/34298264-3bc98460-e71d-11e7-9b37-a24ae30d3107.png)

Related: it needs to include its [own scroll mechanism](https://github.com/Automattic/happychat-client/issues/44) as well.

**Comment by nosolosw** [comment]
@evilluendas do you happen to be around to lend a hand on this next week?

**Comment by evilluendas** [comment]
@nosolosw Yup! Except for Monday, I’ll be around all week 👍
