### ISSUE TITLE
Ending a chat: no visual notice / Agent receives warning that chat is closed when user initiates new chat

### ISSUE THREAD

**Issue by mikeyarce** [Automattic/happychat-client#57]
Not sure if this is meant to be this way, but here's what I'm seeing:

1. User initiates chat
2. Agent /ends chat
3. Nothing changes for the user, it's the same chat window
4. User types in again
5. Agent gets it, but when they respond, there's a note saying the chat is closed

![screen shot 2017-12-22 at 10 15 51 am](https://user-images.githubusercontent.com/3220162/34308286-7eb84ea8-e701-11e7-8f0d-712173296b6c.png)

Ideally when an agent ends a chat the user would be prompted that this is over and would get the option to give feedback, or start a new chat.  Just having the chat stay there with no visual indication of change is odd.

**Comment by nosolosw** [comment]
Moved to https://github.com/Automattic/happychat/issues/1056
