### ISSUE TITLE
Unable to open chat when previous closed chat window is still open

### ISSUE THREAD

**Issue by mikeyarce** [Automattic/happychat-client#59]
This issue might not happen very often, but I wanted to document it anyway.

Steps to reproduce:
1. User initiates chat by going to `create-a-ticket`
2. Agent ends the chat
3. User logs out
4. User logs back in
5. Chat is still "open" on the agent side on the "Recent Chats" section.
6. Happychat notifies you that the user is back!
7.  User is no longer able to see chat form, they only see the ticket form.
8. Agent closes out of chat
9. User still not able to see chat form unless they reload the page.

**Comment by nosolosw** [comment]
I think I fixed this in https://github.com/Automattic/happychat-client/commit/e11488b7880e95d182ba7783825634f8881a632e

For the record, the bug source was the same than https://github.com/Automattic/happychat-client/issues/56 and https://github.com/Automattic/happychat-client/issues/58
